"""Initial migration

Revision ID: 80b0c1c27b5b
Revises: fd9432fc4a2d
Create Date: 2025-02-11 18:25:27.232486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80b0c1c27b5b'
down_revision: Union[str, None] = 'fd9432fc4a2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
